from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
import datetime

def generate_pdf(result, filename="SkillBridge_AI_Report.pdf"):
    """
    Generate a professional PDF report from SkillBridge AI results.
    """
    doc = SimpleDocTemplate(filename, pagesize=(8.5*inch, 11*inch),
                            rightMargin=50, leftMargin=50,
                            topMargin=50, bottomMargin=50)
    
    styles = getSampleStyleSheet()
    
    # Custom title style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=18,
        spaceAfter=20
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        spaceAfter=12,
        textColor=colors.darkblue
    )

    content = []

    # Header
    content.append(Paragraph("🧠 SkillBridge AI Assessment Report", title_style))
    content.append(Paragraph(f"Generated on: {datetime.datetime.now().strftime('%B %d, %Y at %I:%M %p')}", styles['Normal']))
    content.append(Spacer(1, 30))

    # Overall Summary
    content.append(Paragraph("Executive Summary", heading_style))
    content.append(Paragraph(f"Overall Match: <b>{result.get('match_percentage', 0)}%</b>", styles['Normal']))
    content.append(Paragraph(f"Overall Score: <b>{result.get('overall_score', 0)} / 5.0</b>", styles['Normal']))
    content.append(Paragraph(f"Confidence: <b>{result.get('confidence', 0)}%</b>", styles['Normal']))
    content.append(Spacer(1, 20))

    # Summary Text
    summary = result.get("summary", "No summary available.")
    content.append(Paragraph(summary, styles['Normal']))
    content.append(Spacer(1, 25))

    # Skill Breakdown Table
    content.append(Paragraph("Detailed Skill Analysis", heading_style))
    
    table_data = [["Skill", "Required", "Current", "Gap", "Priority"]]
    
    for item in result.get("detailed_results", []):
        table_data.append([
            item.get("skill", "N/A"),
            str(item.get("jd_required", 0)),
            str(item.get("current_level", 0)),
            str(item.get("gap", 0)),
            item.get("priority", "Medium")
        ])

    if len(table_data) > 1:
        table = Table(table_data, colWidths=[2.8*inch, 0.8*inch, 0.8*inch, 0.8*inch, 1.0*inch])
        table_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.lightgrey]),
        ])
        table.setStyle(table_style)
        content.append(table)
    else:
        content.append(Paragraph("No skill data available.", styles['Normal']))

    content.append(Spacer(1, 30))

    # Closing Note
    closing = "This report was generated by SkillBridge AI - an AI tool designed to support career transitions using principles from Organizational Psychology."
    content.append(Paragraph(closing, styles['Normal']))

    # Build the PDF
    doc.build(content)
    return filename
